# 张量（Tensors）

这里将介绍在TensorFlow中创建张量的一些方法。

In [1]:
import tensorflow as tf

sess = tf.Session()

### 1. 固定张量

In [2]:
# 创建指定维度的零张量，tf.zeros([row_dim, col_dim])
zero_tsr = tf.zeros([3,5])
print(zero_tsr)
print(sess.run(zero_tsr))

Tensor("zeros:0", shape=(3, 5), dtype=float32)
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [3]:
# 创建指定维度的单位张量，tf.ones([row_dim, col_dim])
ones_tsr = tf.ones([3,5])
print(ones_tsr)
print(sess.run(ones_tsr))

Tensor("ones:0", shape=(3, 5), dtype=float32)
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [4]:
# 创建指定维度的常数填充的张量，tf.fill([row_dim, col_dim], constant)
filled_tsr = tf.fill([3,5], 42)
print(filled_tsr)
print(sess.run(filled_tsr))

Tensor("Fill:0", shape=(3, 5), dtype=int32)
[[42 42 42 42 42]
 [42 42 42 42 42]
 [42 42 42 42 42]]


In [5]:
# 用已知常数张量创建一个张量，tf.constant([constant, ... , constant])
constant_tsr = tf.constant([1, 2, 3])
print(constant_tsr)
print(sess.run(constant_tsr))

Tensor("Const:0", shape=(3,), dtype=int32)
[1 2 3]


### 2. 相似形状的张量

In [6]:
zeros_similar = tf.zeros_like(constant_tsr)
print(zeros_similar)
print(sess.run(zeros_similar))

Tensor("zeros_like:0", shape=(3,), dtype=int32)
[0 0 0]


In [7]:
ones_similar = tf.ones_like(constant_tsr)
print(ones_similar)
print(sess.run(ones_similar))

Tensor("ones_like:0", shape=(3,), dtype=int32)
[1 1 1]


### 3. 序列张量

In [8]:
# Linspace in TensorFlow
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3) # 生成 [0.0, 0.5, 1.0] ，包含stop
print(linear_tsr)
print(sess.run(linear_tsr))

print('-----------------------------')

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6.0, limit=15.0, delta=3.24)) # 生成 [6, 9, 12] ，不包含limit
sess.run(sequence_var.initializer)
print(sequence_var)
print(sess.run(sequence_var))

# sequence_var在这里是一个变量， 使用tf.Variable来将张量封装成一个变量
# 声明变量之后需要初始化才能使用
# 也可以使用下边的方式来声明
# initialize_op = tf.global_variables_initializer()
# sess.run(initialize_op)

Tensor("LinSpace:0", shape=(3,), dtype=float32)
[ 0.   0.5  1. ]
-----------------------------
<tf.Variable 'Variable:0' shape=(3,) dtype=float32_ref>
[  6.           9.23999977  12.47999954]


### 4. 随机张量

In [9]:
#  tf.random_normal生成正态分布的随机数
rnorm_tsr = tf.random_normal([3, 5], mean=0.0, stddev=1.0)
print(rnorm_tsr)
print(sess.run(rnorm_tsr))

print('-----------------------------')

#  tf.random_uniform生成均匀分布的随机数，从minval（包含minval）到maxval（不包含maxval）
runif_tsr = tf.random_uniform([3, 5], minval=0, maxval=4)
print(runif_tsr)
print(sess.run(runif_tsr))

Tensor("random_normal:0", shape=(3, 5), dtype=float32)
[[-0.86454052  1.23064399  0.05709749 -0.72316289  0.4132866 ]
 [-0.64207602 -0.19469371 -1.41570807 -0.1522173   1.87495553]
 [-0.18220858 -0.31754962  2.0585742   0.16717964 -0.73659074]]
-----------------------------
Tensor("random_uniform:0", shape=(3, 5), dtype=float32)
[[ 1.49200773  2.03896284  2.42357492  1.87910223  1.22865963]
 [ 2.64422226  1.09032917  2.64924955  3.71247578  1.9002037 ]
 [ 0.69299936  1.92370462  2.08023119  1.2543478   0.34999943]]


In [10]:
#  tf.truncated_normal生成带有指定边界的正态分布的随机数
# 其正态分布的随机数位于指定均值（期望）到两个标准差之间的区间
rTruncNorm_tsr = tf.truncated_normal([3, 5], mean=0.0, stddev=1.0)
print(rTruncNorm_tsr)
print(sess.run(rTruncNorm_tsr))

Tensor("truncated_normal:0", shape=(3, 5), dtype=float32)
[[ 0.00932001 -0.67266726  0.52413809 -0.3351168   0.07488699]
 [-0.99693578  0.39037108  1.1598649  -0.71664447  0.50077069]
 [-0.18426307  1.29702401 -1.13656819  1.47332966  1.36240053]]


In [11]:
# 张量/数组的随机化
input_tensor = tf.constant([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

shuffled_output = tf.random_shuffle(input_tensor)
print(shuffled_output)
print(sess.run(shuffled_output))

print('-----------------------------')

cropped_output = tf.random_crop(input_tensor, [1, 3])
print(cropped_output)
print(sess.run(cropped_output))

# tf.random_crop可以实现对张量指定大小的随机裁剪

Tensor("RandomShuffle:0", shape=(2, 5), dtype=int32)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------------------------
Tensor("random_crop:0", shape=(1, 3), dtype=int32)
[[2 3 4]]
